[package]
name = "jwt-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4"
anyhow = "1.0"
base64 = "0.21"
josekit = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.4", features = ["v4"] }
